### ISSUE TITLE
Remove chmod workaround in nextcloud image

### ISSUE THREAD

**Issue by eriksjolund** [eriksjolund/nextcloud-podman#1]
I added the line

https://github.com/eriksjolund/nextcloud-podman/blob/33e32e30880ba9d4cbc5ddf6b0cfa5a712bc1f49/Dockerfile.nextcloud#L2

to work around an error. (I don't remember the details).
Remove the line and create a more secure fix.

**Comment by Shadow8472** [comment]
I might have some additional context. Though my setup isn't to Quadlets yet, I have a pod set up to produce the same UID/GID as the calling rootless user (doesn't work for .hidden_files!). MariaDB and Redis are listed as Running, but Nextcloud is spamming:

```/entrypoint.sh: 111: cannot create /usr/local/etc/php/conf.d/redis-session.ini: Permission denied```

**Comment by Shadow8472** [comment]
I'm past the spamming issue thanks to this comment:
[https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212](
https://github.com/nextcloud/docker/issues/763#issuecomment-1007447212)

Based off discussion, (either around this issue or one linking back to it), I gather it's a Nextcloud container bug when running rootless -- possibly introduced at some point by changes to Docker/Podman, as I do not remember facing this issue when working with Podman 3.0.1. 

Either case, I got new errors when I created a redis-session.ini to mount it as a volume. I'm unsure how this workaround compares in terms of security to the one currently implemented.

**Comment by eriksjolund** [comment]
I wonder if adding `--user 0:0`, would make a change. When I created this repo I thought `--userns keep-id:uid=$gid,gid=$gid` was unrelated to the container UID:GID of the first container process but I noticed last week that it is changed to $uid:$gid.

**Comment by eriksjolund** [comment]
> Either case, I got new errors when I created a redis-session.ini to mount it as a volume. I'm unsure how this workaround compares in terms of security to the one currently implemented.

Do you use bind-mounted dirs or volumes?
In other words `--volume ./dir:dir` or `--volue volumename:dir`?
Probably it doesn't matter but I would first try it out with bind-mounted directories as it is a less complicated operation.

**Comment by Shadow8472** [comment]
I'm using directories. `-v /full/host/path/to/directory:/container/dir:z` I have a non-root podmanuser with a projectNameBase directory for each project. I'm hosting redis-session.ini in ~/nextcloudBase with permissions 644.

I've not made a serious effort to sift through the log (it's Thanksgiving in the US, and I intend to spend most of it with family), but here is one of its current loops. I'm thinking my next step might need to be to bring up PiHole and Caddy to get Nextcloud its domain name.
```
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
==> but the hook folder "before-starting" is empty, so nothing to do
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.88.2.3. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Configuring Redis as session handler
```

**Comment by eriksjolund** [comment]
In the error message output:
```
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
```
That error would happen if the _ip_unprivileged_port_start_ value is higher than 80.
```
$ cat /proc/sys/net/ipv4/ip_unprivileged_port_start
1024
```
Some instructions of how to modify the setting:
https://rootlesscontaine.rs/getting-started/common/sysctl/#allowing-listening-on-tcp--udp-ports-below-1024

Another approach  which is very experimental would be to use a _systemd system service_ with `User=`.
I tried just tried it out for nginx. See example3 and example4 here:
https://github.com/eriksjolund/podman-nginx-socket-activation/tree/main
Note, I have almost not done any testing. I've just verified that a basic curl command was able to download index.html
from the nginx container.

**Comment by Shadow8472** [comment]
What I know is I'm totally burned out from focusing on this topic this month. I'll be back, but I want to do some less intense blog topics over December and come back at it in the new year. My immediate goal is to get PiHole and Caddy into Quadlets so I have something to work off of come January. I'm to the point of generating Kubernetes .yml files for running pods.

**Comment by Shadow8472** [comment]
For the record, Alternate Solution 2 as implemented by setting `--user 0:0` to the container (leaving the pod at `--userns=keep-id:uid=999,gid=999`) resulted in the same log including `(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80`

**Comment by eriksjolund** [comment]
An install script now creates an empty file _redis-session.ini_


https://github.com/eriksjolund/nextcloud-podman/blob/9b01bdfa282f84d6a5b4d18cd9df5d62ae9e0ea2/install.sh#L18

The file is bind-mounted into the nextcloud container:

https://github.com/eriksjolund/nextcloud-podman/blob/9b01bdfa282f84d6a5b4d18cd9df5d62ae9e0ea2/nextcloud.container#L22

**Comment by eriksjolund** [comment]
Closed by https://github.com/eriksjolund/nextcloud-podman/pull/2
